[project]
authors = ["hastmark <hastmark2001@hotmail.com>"]
channels = ["conda-forge"]
description = "This tool enables a cli for fuzzy finding for folders"
name = "fzf-folder"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
clean = 'rm -rf out'
generate = 'cmake -S . -B out -G Ninja -DCMAKE_TOOLCHAIN_FILE=../TC-clang.cmake -DCMAKE_BUILD_TYPE=Debug'
build = 'cmake --build out'
release = 'cmake -S . -B out -G Ninja -DCMAKE_TOOLCHAIN_FILE=../TC-clang.cmake -DCMAKE_BUILD_TYPE=Release; cmake --build out'

[dependencies]
cmake = ">=3.30.5,<4"
clang = ">=19.1.3,<20"
ninja = ">=1.12.1,<2"
